name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Inject build date and run number into version string
      - name: Set build info
        run: |
          sed -i "s/__BUILD_DATE__/$(date +'%Y%m%d')/g" index.html
          sed -i "s/__BUILD_NUMBER__/${{ github.run_number }}/g" index.html

      # Create zip
      - name: Create zip
        run: |
          mkdir deploy
          zip -r deploy/site.zip . \
            -x "*.git*" \
            -x "deploy/*"

      # Upload ONLY deploy folder
      - name: Upload repository
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            protocol: ftp
            port: 21
            security: loose
            local-dir: ./
            server-dir: /309aircadets.co.uk/htdocs/
            timeout: 600000

      # Extract on server
      - name: Trigger deploy
        run: curl https://309aircadets.co.uk/deploy.php